# Generated by Django 4.2.16 on 2025-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatus",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
