# Generated by Django 4.2.16 on 2025-09-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_tranding',
            new_name='is_arrival',
        ),
    ]
